name: CybCore checks
on:
  pull_request:
  push:
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check server
        working-directory: cybcore/server
        run: cargo check --all-targets
      - name: Tests
        working-directory: cybcore/server
        run: cargo test --all-targets
