pub mod web;
pub mod web_urls;
pub mod web_html;
pub mod web_parse;
pub mod web_search;
pub mod web_fetch;
pub mod lan;
pub mod secure_chat;
pub mod proximity;
#[cfg(target_os = "macos")]
pub mod ble_advertiser;
#[cfg(not(target_os = "macos"))]
#[path = "ble_advertiser_stub.rs"]
pub mod ble_advertiser;
#[cfg(target_os = "macos")]
pub mod ble;
#[cfg(not(target_os = "macos"))]
#[path = "ble_stub.rs"]
pub mod ble;
pub mod mesh;
pub mod vpn;
pub mod browser;
